const data={
    "isVip":false,
    "int":0,
    "rule":{
        "bgcolor":"#d8ebf3",
        "rule_color":"#5d5a83",
        "textios":[
            "活动时间：2017年7月17日10点-2017年7月24日0点",
            "充值赠送：单次(一次性)充值达到指定额度，则赠送对应额度阅券，多充多送!",
            "活动赠送阅券实时到账，有效期为7天，可用于直接购买书籍",
            "本次活动赠送的积分实时到账，在活动期间有效，可以开宝箱和累计冲榜",
            "本活动最终解释权归QQ阅读所有，与苹果公司无关"
        ],
         "textadr":[
            "活动时间：2017年7月17日10点-2017年7月24日0点",
            "充值赠送：单次(一次性)充值达到指定额度，则赠送对应额度书券和积分，多充多送!",
            "活动赠送书券实时到账，有效期为7天，可用于直接购买书籍",
            "本次活动赠送的积分实时到账，在活动期间有效，可以开宝箱和累计冲榜"
        ],
        "rule_hd":"img/rule.png",
        "bottom_bg":"img/rulebg.png",
        "copyright_color":"#999999"
    },
    "name":"暑期充赠",
    "card":{
        "card_font":"#5c5a85",
        "bg_start":"#d8ebf3",
        "btn_shadow":"#d66657",
        "bg_end":"#eaedf1",
        "card_border":"#c5cddd",
        "tag_shadow":"#348478",
        "listadr":[
            {
                "charge":10,
                "coin":1000,
                "coupon":"58"
            },
            {
                "charge":500,
                "coin":50000,
                "coupon":"5000"
            },
            {
                "charge":20,
                "coin":2000,
                "coupon":"128"
            },
            
            {
                "charge":50,
                "coin":5000,
                "coupon":"328"
            },
            {
                "charge":100,
                "coin":10000,
                "coupon":"888"
            },
            {
                "charge":200,
                "coin":20000,
                "coupon":"1888"
            }
        ],
        "listios":[
            {
                "charge":12,
                "coin":1200,
                "coupon":"68"
            },
            {
                "charge":30,
                "coin":3000,
                "coupon":"188"
            },
            {
                "charge":98,
                "coin":9800,
                "coupon":"888"
            },
            
            {
                "charge":618,
                "coin":61800,
                "coupon":"6180"
            }
        ],
        "tag_bg":"#469c8f",
        "card_bg":"#fff",
        "btn_bg":"#ee6a57"
    },
    "banner":window.pt == "ios" ? "img/bannerios.jpg" : "img/banner.jpg"
}

export default data;