var data={
    "code":1,
    "isLogin":true,
    "isVip":true,
    "msg":"init success~",
    //配置数据
    "pictureAndStyle":{
        "bodycolor":"#fff7e7",//body背景色
        "color1":"#FE5D62", //文字颜色 
        "color2":"#3fbc82", //按钮颜色
        "banner":"images/banner.jpg",//活动页banner图
        "tab":"images/tab3.png",//tab图
        "title1":"images/m1.png",//一口价标题
        "title2":"images/m2.png",//N元购标题  
        "columnbg1":"images/columnbg1.png",//一口价模块背景
        "columnbg2":"images/columnbg2.png", //n元购模块背景
        "hot":"images/hot.png",//热门图标
        "tag":"images/tag.png",//n元购模块的价格标签
        "sharebtnText":"喊小伙伴参加",//分享按钮上的文案
        "rule":["活动时间：2017年2月23日-2017年2月28日；","活动期间，可以按照优惠价格购买相应书籍现有章节的在线阅读权，活动结束后，已购买章节可继续免费在线阅读，新出更新章节需订阅阅读","通过活动购买的书籍仅可以通过QQ阅读客户端内在线阅读，不可下载"],
         "sharebanner":"images/sharebanner.jpg",//分享页banner图
         "sharecover":"images/cover.jpg",//分享图标
         "sharetitle":"我是分享标题",//分享标题
         "sharedesc":"我是分享描述"//分享描述
    },
     //页面数据    n元购
    "userHasChoicePackageId":[
        null,
        null,
        "0_1_4"
    ],
    "choiceNumber":[
        "10",
        "11",
        "14"
    ],
    "choosePackage":[
        {
            "bagName":"书包1",
            "bookInfo":[
                {"author":"舒静庐","bid":223001,"cover":"https:\/\/static.reader.qq.com\/cover\/1\/223001\/b_223001.jpg","price":"1.00","title":"儿女的孝心：把幸福与健康送给老爸老妈"},
                {"author":"吉米","bid":222999,"cover":"https:\/\/static.reader.qq.com\/cover\/999\/222999\/b_222999.jpg","price":"1.00","title":"月光下的迷情女孩：帅哥真坏，美眉真野"},
                {"author":"侯书森 邱卫东","bid":223000,"cover":"https:\/\/static.reader.qq.com\/cover\/0\/223000\/b_223000.jpg","price":"1.00","title":"猪八戒是个好男人"},
                {"author":"曹金洪","bid":223048,"cover":"https:\/\/static.reader.qq.com\/cover\/48\/223048\/b_223048.jpg","price":"1.00","title":"人是自身幸福的设计师（经典智慧系列）"},
                {"author":"椰海","bid":223049,"cover":"https:\/\/static.reader.qq.com\/cover\/49\/223049\/b_223049.jpg","price":"1.00","title":"梦惑"},
                {"author":"曹金洪","bid":223050,"cover":"https:\/\/static.reader.qq.com\/cover\/50\/223050\/b_223050.jpg","price":"1.00","title":"容易走的都是下坡路（经典智慧系列）"},
            ],
            "discountBagMoney":"400",
            "originalBagMoney":"500"
        },
        {
            "bagName":"书包2",
            "bookInfo":[
                {"author":"舒静庐","bid":223001,"cover":"https:\/\/static.reader.qq.com\/cover\/1\/223001\/b_223001.jpg","price":"1.00","title":"儿女的孝心：把幸福与健康送给老爸老妈"},
                {"author":"吉米","bid":222999,"cover":"https:\/\/static.reader.qq.com\/cover\/999\/222999\/b_222999.jpg","price":"1.00","title":"月光下的迷情女孩：帅哥真坏，美眉真野"},
                {"author":"侯书森 邱卫东","bid":223000,"cover":"https:\/\/static.reader.qq.com\/cover\/0\/223000\/b_223000.jpg","price":"1.00","title":"猪八戒是个好男人"},
                {"author":"曹金洪","bid":223048,"cover":"https:\/\/static.reader.qq.com\/cover\/48\/223048\/b_223048.jpg","price":"1.00","title":"人是自身幸福的设计师（经典智慧系列）"},
                {"author":"椰海","bid":223049,"cover":"https:\/\/static.reader.qq.com\/cover\/49\/223049\/b_223049.jpg","price":"1.00","title":"梦惑"},
                {"author":"曹金洪","bid":223050,"cover":"https:\/\/static.reader.qq.com\/cover\/50\/223050\/b_223050.jpg","price":"1.00","title":"容易走的都是下坡路（经典智慧系列）"},
            ],
            "discountBagMoney":"600",
            "originalBagMoney":"700"
        },
         {
            "bagName":"书包3",
            "bookInfo":[
                {"author":"舒静庐","bid":223001,"cover":"https:\/\/static.reader.qq.com\/cover\/1\/223001\/b_223001.jpg","price":"1.00","title":"儿女的孝心：把幸福与健康送给老爸老妈"},
                {"author":"吉米","bid":222999,"cover":"https:\/\/static.reader.qq.com\/cover\/999\/222999\/b_222999.jpg","price":"1.00","title":"月光下的迷情女孩：帅哥真坏，美眉真野"},
                {"author":"侯书森 邱卫东","bid":223000,"cover":"https:\/\/static.reader.qq.com\/cover\/0\/223000\/b_223000.jpg","price":"1.00","title":"猪八戒是个好男人"},
                {"author":"曹金洪","bid":223048,"cover":"https:\/\/static.reader.qq.com\/cover\/48\/223048\/b_223048.jpg","price":"1.00","title":"人是自身幸福的设计师（经典智慧系列）"},
                {"author":"椰海","bid":223049,"cover":"https:\/\/static.reader.qq.com\/cover\/49\/223049\/b_223049.jpg","price":"1.00","title":"梦惑"},
                {"author":"曹金洪","bid":223050,"cover":"https:\/\/static.reader.qq.com\/cover\/50\/223050\/b_223050.jpg","price":"1.00","title":"容易走的都是下坡路（经典智慧系列）"},
            ],
            "discountBagMoney":"100",
            "originalBagMoney":"200"
        }
    ],    
    //页面数据  一元购
    "userHasBoughtPackageId":[
        "1"
    ],  
    "batchNumber":[
        "10",
        "18",
        "12"
    ],
    "batchPackage":[
        {
            "bagName":"仙道秘术11",
            "bookInfo":[
                {
                    "author":"卜汀",
                    "cover":"https://static.reader.qq.com/cover/495/234495/b_234495.jpg",
                    "title":"官娶鬼女",
                    "bid":"234495"
                },
                {
                    "author":"妖天",
                    "cover":"https://static.reader.qq.com/cover/347/239347/b_239347.jpg",
                    "title":"万古独尊",
                    "bid":"239347"
                },
                {
                    "author":"青青子墨",
                    "cover":"https://static.reader.qq.com/cover/759/219759/b_219759.jpg",
                    "title":"帝王神诀",
                    "bid":"216395"
                }
            ],
            "discountBagMoney":29.99,
            "originalBagMoney":499.85
        },
        {
            "bagName":"仙道秘术22",
            "bookInfo":[
                {
                    "author":"卜汀",
                    "cover":"https://static.reader.qq.com/cover/495/234495/b_234495.jpg",
                    "title":"官娶鬼女",
                    "bid":"234495"
                },
                {
                    "author":"妖天",
                    "cover":"https://static.reader.qq.com/cover/347/239347/b_239347.jpg",
                    "title":"万古独尊",
                    "bid":"239347"
                },
                {
                    "author":"青青子墨",
                    "cover":"https://static.reader.qq.com/cover/759/219759/b_219759.jpg",
                    "title":"帝王神诀",
                    "bid":"216395"
                }
            ],
            "discountBagMoney":29.99,
            "originalBagMoney":499.85
        },
        {
            "bagName":"仙道秘术33",
            "bookInfo":[
                {
                    "author":"卜汀",
                    "cover":"https://static.reader.qq.com/cover/495/234495/b_234495.jpg",
                    "title":"官娶鬼女",
                    "bid":"234495"
                },
                {
                    "author":"妖天",
                    "cover":"https://static.reader.qq.com/cover/347/239347/b_239347.jpg",
                    "title":"万古独尊",
                    "bid":"239347"
                },
                {
                    "author":"青青子墨",
                    "cover":"https://static.reader.qq.com/cover/759/219759/b_219759.jpg",
                    "title":"帝王神诀",
                    "bid":"216395"
                }
            ],
            "discountBagMoney":29.99,
            "originalBagMoney":499.85
        },
    ],
    //账户余额
    "money":10000, 
    "z_money":0
}
module.exports=data;
// export default data;