var data={
   "isLogin":false,
    "uid":3537879607,
    "index":4,
    "isVip":false,
    "gd":1,
    "code":1,
    "canPick":true,
    "userNick":"pilabiala",
    "batchNumber":"1234",
    "choiceNumber":"123489",
    "lt":1,
    "timeTable":[
        {
            "first":"16:00",
            "second":"武侠4"
        },
        {
            "first":"18:00",
            "second":"武侠5"
        },
        {
            "first":"20:00",
            "second":"武侠6"
        },
        {
            "first":"22:00",
            "second":"武侠7"
        },
        {
            "first":"08:00",
            "second":"武侠"
        },
        {
            "first":"10:00",
            "second":"武侠"
        },
        {
            "first":"12:00",
            "second":"武侠"
        },
        {
            "first":"14:00",
            "second":"武侠"
        }
    ],
    "msg":" init",
    "BookList":[
        {
            "batchSaleBook":{
                "batch":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "chooseSaleBook":{
                "choose":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"123",
                "packageTopic":"name"
            },
            "flashSaleBook":{
                "author":"鸿蒙树",
                "bid":264082,
                "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                "price":"price",
                "title":"天才透视眼0"
            },
            "topicName":"武侠4"
        },
        {
            "batchSaleBook":{
                "batch":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "chooseSaleBook":{
                "choose":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "flashSaleBook":{
                "author":"鸿蒙树",
                "bid":264082,
                "cover":"https://static.reader.qq.com/cover/840/484840/b_484840.jpg",
                "price":"price",
                "title":"天才透视眼1"
            },
            "topicName":"武侠5"
        },
        {
            "batchSaleBook":{
                "batch":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "chooseSaleBook":{
                "choose":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "flashSaleBook":{
                "author":"鸿蒙树",
                "bid":264082,
                "cover":"https://static.reader.qq.com/cover/371/14593371/b_14593371.jpg",
                "price":"price",
                "title":"天才透视眼2"
            },
            "topicName":"武侠6"
        },
        {
            "batchSaleBook":{
                "batch":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "chooseSaleBook":{
                "choose":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "flashSaleBook":{
                "author":"鸿蒙树",
                "bid":264082,
                "cover":"https://static.reader.qq.com/cover/170/832170/b_832170.jpg",
                "price":"price",
                "title":"天才透视眼3"
            },
            "topicName":"武侠7"
        },
        {
            "batchSaleBook":{
                "batch":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "chooseSaleBook":{
                "choose":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "flashSaleBook":{
                "author":"鸿蒙树",
                "bid":264082,
                "cover":"https://static.reader.qq.com/cover/239/11365239/b_11365239.jpg",
                "price":"price",
                "title":"天才透视眼4"
            },
            "topicName":"武侠"
        },
        {
            "batchSaleBook":{
                "batch":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "chooseSaleBook":{
                "choose":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "flashSaleBook":{
                "author":"鸿蒙树",
                "bid":264082,
                "cover":"https://static.reader.qq.com/cover/921/464921/b_464921.jpg",
                "price":"price",
                "title":"天才透视眼5"
            },
            "topicName":"武侠"
        },
        {
            "batchSaleBook":{
                "batch":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "chooseSaleBook":{
                "choose":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "flashSaleBook":{
                "author":"鸿蒙树",
                "bid":264082,
                "cover":"https://static.reader.qq.com/cover/530/486530/b_486530.jpg",
                "price":"price",
                "title":"天才透视眼6"
            },
            "topicName":"武侠"
        },
        {
            "batchSaleBook":{
                "batch":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "chooseSaleBook":{
                "choose":[
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    },
                    {
                        "author":"鸿蒙树",
                        "bid":264082,
                        "cover":"https://static.reader.qq.com/cover/82/264082/b_264082.jpg",
                        "price":"price",
                        "title":"天才透视眼"
                    }
                ],
                "packageMoney":"money",
                "packageTopic":"name"
            },
            "flashSaleBook":{
                "author":"鸿蒙树",
                "bid":264082,
                "cover":"https://static.reader.qq.com/cover/914/486914/b_486914.jpg",
                "price":"price",
                "title":"天才透视眼7"
            },
            "topicName":"武侠"
        }
    ],
    "flashNumber":"123"
}
module.exports=data;
// export default data;