var readpack={
    "qq":null,
    "code":"0",
    "guin":null,
    "weekExchangeInfo":{
        "needReadTime":0,
        "canExchangeBilling":true,
        "weekId":"20170410",
        "weekReadTime":0,
        "exchangedBilling":0,
        "exchangeDetailList":[
            {
                "isCrit":true,
                "readTime":10,
                "type":2,
                "billing":10
            },
            {
                "isCrit":false,
                "readTime":30,
                "type":0,
                "billing":10
            },
            {
                "isCrit":false,
                "readTime":90,
                "type":2,
                "billing":10
            },
            {
                "isCrit":true,
                "readTime":180,
                "type":0,
                "billing":10
            },
            {
                "isCrit":false,
                "readTime":360,
                "type":2,
                "billing":10
            },
            {
                "isCrit":false,
                "readTime":600,
                "type":2,
                "billing":10
            },
            {
                "isCrit":false,
                "readTime":960,
                "type":2,
                "billing":10
            }
        ],
        "hasFinishExchange":false,
        "exchangedIndex":-1,
        "critRange":"1.1-5.5",
        "critIndex":0,
        "rankRatio":0,
        "critNum":10,     
    },
    "prefer":1,
    "icon":"https://q4.qlogo.cn/g?b=qq&k=BgyEM9pReogznibiab7sibjoQ&s=100&t=552",
    "channel":"00000",
    "version":null,
    "isVip":false,
    "sid":null,
    "nick":"测试1",
    "isLogin":true,
    "guestcheckcode":0
};
var result={
    exchangedBilling:10,
    code:0
}
module.exports={readpack,result};
// export default data;