const boxs=[
    {
        card:0,
        name:"限量宝箱",
        score:300,
        classname:"box limitbox",
        rest:100,
        title:"limitbox.png",
        prizes:[
            {
                name:"公仔",
                pic:"p1.png",
                link:true,
                intro:"亲切熟悉的经典企鹅形象公仔，将于活动结束后10个工作日内发放",
                id:0
            },
            {
                name:"500元京东卡",
                pic:"p2.png",
                link:true,
                intro:"此奖励为实物卡，用于在京东购物时抵扣500元，将于活动结束后10个工作日内发放",
                id:1
            },
            {
                name:"笔记本电脑",
                pic:"p3.png",
                link:true,
                intro:"联想小新Air 13 Pro笔记本，将于活动结束后10个工作日内发放",
                id:2
            }
        ]       
    },
    {
        card:4,
        name:"铜宝箱",
        score:10,
        classname:"box copperbox",
        title:"copperbox.png",
        prizes:[
            {
                name:"1Q币",
                pic:"p4.png",
                qq:true,
                intro:"将于活动结束后10个工作日内发放，默认发登录账户，ios游客及微信登录请认真填写账号哦",
                id:3
            },
            {
                name:"30抵扣券",
                pic:"p5.png",
                expire:true,
                intro:"用于购买指定分类书籍时当做书币/阅点抵扣，获奖后即刻到账",
                id:4
            }
        ]       
    },
    {
        card:3,
        name:"银宝箱",
        score:50,
        classname:"box silverbox",
        title:"silverbox.png",
        prizes:[
            {
                name:"2Q币",
                pic:"p4.png",
                qq:true,
                intro:"将于活动结束后10个工作日内发放，默认发登录账户，ios游客及微信登录请认真填写账号哦",
                id:5
            },
            {
                name:"150抵扣券",
                pic:"p5.png",
                expire:true,
                intro:"用于购买指定分类书籍时当做书币/阅点抵扣，获奖后即刻到账",
                id:6
            }
        ]       
    },
    {
        card:2,
        name:"金宝箱",
        score:100,
        classname:"box goldbox",
        title:"goldbox.png",
        prizes:[
            {
                name:"QQ二合一数据线",
                pic:"p6.png",
                link:true,
                intro:"美貌的二合一数据线，将于活动结束后10个工作日内发放",
                id:9
            },
            {
                name:"5Q币",
                pic:"p4.png",
                qq:true,
                intro:"将于活动结束后10个工作日内发放，默认发登录账户，ios游客及微信登录请认真填写账号哦",
                id:7
            },
            {
                name:"300抵扣券",
                pic:"p5.png",
                expire:true,
                intro:"用于购买指定分类书籍时当做书币/阅点抵扣，获奖后即刻到账",
                id:8
            }         
        ]       
    },
    {
        card:1,
        name:"钻石宝箱",
        score:200,
        classname:"box diamondbox",
        title:"diamondbox.png",
        prizes:[
            {
                name:"QQfamily彩色笔记本",
                pic:"p7.png",
                link:true,
                intro:"封面有QQfamily家族公仔的形象的笔记本，将于活动结束后10个工作日内发放",
                id:12
            },
            {
                name:"10Q币",
                pic:"p4.png",
                qq:true,
                intro:"将于活动结束后10个工作日内发放，默认发登录账户，ios游客及微信登录请认真填写账号哦",
                id:10
            },
            {
                name:"500抵扣券",
                pic:"p5.png",
                expire:true,
                intro:"用于购买指定分类书籍时当做书币/阅点抵扣，获奖后即刻到账",
                id:11
            }           
        ]       
    }
]
export default boxs;