var data={
    "isLogin":true,
    "isVip":true,
    "code":1,
    "userHasBoughtPackageId":[
        "1"
    ],
    "msg":"init success~",
    "isBlackUser":false,
    "userHasChoicePackageId":[
        null,
        null,
        "0_1_4"
    ],
    "z_money":0,
    "choosePackage1":{
        "bagName":"新锐作者（29.99）",
        "bookInfo":[
            {
                "author":"王小秋",
                "cover":"https://static.reader.qq.com/cover/506/13515506/b_13515506.jpg",
                "title":"极品小农夫",
                "bid":"13515506"
            },
            {
                "author":"萧潜",
                "cover":"https://static.reader.qq.com/cover/170/832170/b_832170.jpg",
                "title":"超凡传",
                "bid":"832170"
            },
            {
                "author":"无相1",
                "cover":"https://static.reader.qq.com/cover/371/14593371/b_14593371.jpg",
                "title":"最强透视小神医",
                "bid":"14593371"
            },
            {
                "author":"远瞳",
                "cover":"https://static.reader.qq.com/cover/75/503075/b_503075.jpg",
                "title":"异常生物见闻录",
                "bid":"503075"
            },
            {
                "author":"误道者",
                "cover":"https://static.reader.qq.com/cover/840/484840/b_484840.jpg",
                "title":"大道争锋",
                "bid":"484840"
            },
            {
                "author":"小黑醉酒",
                "cover":"https://static.reader.qq.com/cover/239/11365239/b_11365239.jpg",
                "title":"权驭大明",
                "bid":"11365239"
            }
        ],
        "money":29.9
    },
    "choosePackage0":{
        "bagName":"顶级白金（39.99）",
        "bookInfo":[
            {
                "author":"唐家三少",
                "cover":"https://static.reader.qq.com/cover/921/464921/b_464921.jpg",
                "title":"生肖守护神",
                "bid":"464921"
            },
            {
                "author":"血红",
                "cover":"https://static.reader.qq.com/cover/530/486530/b_486530.jpg",
                "title":"光明纪元",
                "bid":"486530"
            },
            {
                "author":"猫腻",
                "cover":"https://static.reader.qq.com/cover/592/462592/b_462592.jpg",
                "title":"庆余年",
                "bid":"462592"
            },
            {
                "author":"骷髅精灵",
                "cover":"https://static.reader.qq.com/cover/914/486914/b_486914.jpg",
                "title":"圣堂",
                "bid":"486914"
            },
            {
                "author":"林海听涛",
                "cover":"https://static.reader.qq.com/cover/672/489672/b_489672.jpg",
                "title":"胜者为王",
                "bid":"489672"
            },
            {
                "author":"蝴蝶蓝",
                "cover":"https://static.reader.qq.com/cover/594/462594/b_462594.jpg",
                "title":"天醒之路",
                "bid":"462594"
            }
        ],
        "money":39.99
    },
    "choosePackage2":{
        "bagName":"书友热搜（19.99）",
        "bookInfo":[
            {
                "author":"寂无",
                "cover":"https://static.reader.qq.com/cover/593/375593/b_375593.jpg",
                "title":"校花之高手无敌",
                "bid":"375593"
            },
            {
                "author":"安七夜",
                "cover":"https://static.reader.qq.com/cover/138/342138/b_342138.jpg",
                "title":"不死武帝",
                "bid":"342138"
            },
            {
                "author":"乱舞沙",
                "cover":"https://static.reader.qq.com/cover/383/13666383/b_13666383.jpg",
                "title":"最强特种兵之战神传说",
                "bid":"13666383"
            },
            {
                "author":"冲天雨",
                "cover":"https://static.reader.qq.com/cover/944/14084944/b_14084944.jpg",
                "title":"茅山之最强捉鬼人",
                "bid":"14084944"
            },
            {
                "author":"zhttty",
                "cover":"https://static.reader.qq.com/cover/705/812705/b_812705.jpg",
                "title":"侠行天下",
                "bid":"812705"
            },
            {
                "author":"鸿蒙树",
                "cover":"https://static.reader.qq.com/cover/380/13900380/b_13900380.jpg",
                "title":"妙手小医仙",
                "bid":"13900380"
            }
        ],
        "money":19.9
    },
    "batchNumber":[
        "10",
        "18",
        "12"
    ],
    "money":548,
    "batchPackage1":{
        "bagName":"仙道秘术",
        "bookInfo":[
            {
                "author":"卜汀",
                "cover":"https://static.reader.qq.com/cover/495/234495/b_234495.jpg",
                "title":"官娶鬼女",
                "bid":"234495"
            },
            {
                "author":"妖天",
                "cover":"https://static.reader.qq.com/cover/347/239347/b_239347.jpg",
                "title":"万古独尊",
                "bid":"239347"
            },
            {
                "author":"青青子墨",
                "cover":"https://static.reader.qq.com/cover/759/219759/b_219759.jpg",
                "title":"帝王神诀",
                "bid":"216395"
            }
        ],
        "discountBagMoney":29.99,
        "originalBagMoney":499.85
    },
    "batchPackage2":{
        "bagName":"重生逆袭",
        "bookInfo":[
            {
                "author":"月武罗",
                "cover":"https://static.reader.qq.com/cover/350/234350/b_234350.jpg",
                "title":"异能时代",
                "bid":"234350"
            },
            {
                "author":"乱舞沙",
                "cover":"https://static.reader.qq.com/cover/273/683273/b_683273.jpg",
                "title":"抗日之天狼突击队",
                "bid":"683273"
            },
            {
                "author":"河图少年",
                "cover":"https://static.reader.qq.com/cover/949/11314949/b_11314949.jpg",
                "title":"我的契约总裁老婆",
                "bid":"11314949"
            }
        ],
        "discountBagMoney":29.99,
        "originalBagMoney":481.01
    },
    "batchPackage0":{
        "bagName":"热血爽文",
        "bookInfo":[
            {
                "author":"环首刀",
                "cover":"https://static.reader.qq.com/cover/278/11330278/b_11330278.jpg",
                "title":"霸道农民俏村花",
                "bid":"11330278"
            },
            {
                "author":"流水曲觞",
                "cover":"https://static.reader.qq.com/cover/409/629409/b_629409.jpg",
                "title":"万古神王",
                "bid":"629409"
            },
            {
                "author":"综合班",
                "cover":"https://static.reader.qq.com/cover/626/14171626/b_14171626.jpg",
                "title":"神级少林弟子",
                "bid":"14171626"
            }
        ],
        "discountBagMoney":29.99,
        "originalBagMoney":240.18
    },
    "choiceNumber":[
        "10",
        "11",
        "14"
    ]
}
module.exports=data;
// export default data;